language: python
python:
  - "3.4"
  - "3.6"
  - "3.7"
  - "nightly"
install:
  - pip install -r requirements-build.txt -r requirements-runtime.txt
script:
  - python -m unittest discover -s tests
deploy:
  provider: pypi
  username: ...
  password: ...
  on:
    tags: true
