fr:
    # Si présent, ce motif sera utilisé pour formater tous les messages envoyés
    all_messages: 🤖 %{message}

    # Ce message est envoyé lorsque le bot ne sait pas traduire le message demandé
    IDontKnow: Je ne sais pas

    # Remplacez ces messages par une chaîne vide "" afin de les désactiver
    Hello: nicobot paré 🤟
    Goodbye: A+ 👋

    #####################
    # COMMANDS
    #
    # The following patterns are used to detect commands in the received messages
    #####################

    # Si un message correspond à ce motif, le bot tentera de le traduire dans la langue locale configurée
    # Voir https://docs.python.org/3/howto/regex.html#regex-howto pour le format
    # Matching is made with case ignored
    # TODO rename to pattern_translate_default_locale to make it clear it's not a text to localize
    translate_default_locale: '@?nicobot\s+(?P<message>.+)$'

    # Si un message correspond à ce motif, le bot tentera de traduire <message> dans la langue <language>
    # Voir https://docs.python.org/3/howto/regex.html#regex-howto pour le format
    # Matching is made with case ignored
    # TODO rename to pattern_translate to make it clear it's not a text to localize
    translate: '@?nicobot\s+(?P<message>.+)\s+en\s+(?P<language>.+)$'

    # Phrase clé pour éteindre le bot
    # Matching is made with case ignored
    Shutdown: couché nicobot
